### ISSUE TITLE
trouble creating thelonious chains on latest develop

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/epm-go#157] opened 2015-04-24 20:05 UTC
The following happened when  trying to create a thelonious chain

```
dennis@Juzo:~$ rm -rf .decerver
dennis@Juzo:~$ epm init
dennis@Juzo:~$ epm new -type thel -name bob -o
Chain type: thelonious
Chain type: thelonious
thel
2015/04/24 16:00:37 [EPM-CLI] Missing genesis.json!
dennis@Juzo:~$ epm refs
There is no chain checked out
```

It works for eth (as expected if its a problem with the genesis config.

**Comment by compleatang** [comment] 2015-04-25 12:05
Closing as a duplicate of https://github.com/eris-ltd/thelonious/issues/93

**Closed by compleatang** 2015-04-25 12:05 UTC
